Repository AdityaTD/PenguBot, pull requests merged in 2020-04, with the labels that each got.

#173 Fix typo - ER_TRY_AGAIN string
  src/languages/en-US.js
  src/languages/es-ES.js
  src/languages/fr-FR.js
Labels: SEM: Patch

#174 Remove: snekfetch dependency
  package.json
  src/PenguBot.js
  src/commands/Developer/eval.js
  src/commands/Game Statistics/clashofclans.js
  src/commands/Game Statistics/clashroyale.js
  src/commands/Game Statistics/csgo.js
  src/commands/Game Statistics/fortnite.js
  src/commands/Images/cat.js
  src/commands/Images/cuddle.js
  src/commands/Images/dog.js
  src/commands/Images/feed.js
  src/commands/Images/fox.js
  src/commands/Images/hug.js
  src/commands/Images/kiss.js
  src/commands/Images/pat.js
  src/commands/Images/poke.js
  src/commands/Images/randomcomic.js
  src/commands/Images/slap.js
  src/commands/Images/tickle.js
  src/commands/NSFW/nekos.js
  src/commands/Profiles/profile.js
  src/commands/Profiles/rank.js
  src/commands/Utilities/poll.js
  src/commands/Utilities/shorten.js
  src/commands/Utilities/twstats.js
  src/commands/Utilities/urban.js
  src/commands/Utilities/weather.js
  src/lib/tags/getjson.js
  src/monitors/memberProfiles.js
  src/monitors/perspectivemod.js
  src/monitors/profiles.js
  src/tasks/spotify.js
Labels: Meta: Dependencies, Meta: Enhancement, Meta: Refactor, SEM: Major

#175 Fix(flags): flags > flagArgs
  src/commands/Developer/eval.js
  src/commands/Developer/exec.js
  src/commands/Moderation/ban.js
  src/commands/Moderation/mute.js
  src/commands/Moderation/softban.js
  src/commands/Music/skip.js
  src/inhibitors/requireMusic.js
Labels: Meta: Enhancement, Meta: Refactor, SEM: Patch
